sudo: required
services:
  - docker

before_install:
  - docker build -t jerrymajewski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jerrymajewski/react-test npm test -- --coverage

after_success:
  - docker build -t jerrymajewski/multi-client ./client
  - docker build -t jerrymajewski/multi-nginx ./nginx
  - docker build -t jerrymajewski/multi-server ./server
  - docker build -t jerrymajewski/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin
  - docker push jerrymajewski/multi-client
  - docker push jerrymajewski/multi-nginx
  - docker push jerrymajewski/multi-server
  - docker push jerrymajewski/multi-worker
